version: "3.7"

services:
    local-db:
        image: postgres:13.3-alpine
        ports:
            - 127.0.0.1:5432:5432
        environment:
        - POSTGRES_USER=ezyuser
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=ezytutors